"""Independent expected values generated by the original audited paper module."""
import json
from pathlib import Path
import numpy as np
from xpsych import _geometry as g, geometry as rsa


def test_all_paper_functions_against_original_outputs():
    data = json.loads((Path(__file__).parent / 'fixtures/geometry_reference.json').read_text())
    x, y, a = [np.array(data[k]) for k in ('x', 'y', 'a')]
    groups, people = np.array(data['groups']), np.array(data['people'])
    c, m, r = np.cov(x.T), a.T @ a, np.corrcoef(y.T)
    outputs = {
        'upper': g.upper(c), 'corr': g.cov_to_corr(c), 'power': g.sym_power(m, -.5),
        'whiten': g.whiten(c, m), 'deconvolve': g.deconvolve(c, m, np.eye(7)*.01),
        'deconvolve_wording': g.deconvolve_wording(.3*m@r@m+2*m, m),
        'center': g.center_by_group(x, groups, people),
        'reliability': g.split_half_reliability(x, lambda t: np.corrcoef(t.T), n_splits=20, rng=18),
        'partial': g.partial_corr(g.upper(c), g.upper(r), g.upper(m)),
        'mantel': g.mantel(c, r, n_perm=99, rng=11),
        'mantel_control': g.mantel(c, r, control=m, n_perm=99, rng=11),
        'fl': g.mantel_partial_fl(c, r, m, n_perm=99, rng=11),
        'keyed': g.keyed_scores(x, {'scale': [(0, 1), (3, -1), (5, .5)]})['scale'],
    }
    for key, result in outputs.items():
        if key == 'deconvolve_wording':
            for actual, expected in zip(result, data['expected'][key]):
                np.testing.assert_allclose(actual, expected, rtol=1e-10, atol=1e-12)
        else:
            np.testing.assert_allclose(result, data['expected'][key], rtol=1e-10, atol=1e-12)
    np.testing.assert_allclose(rsa.center_by_group(x, groups.astype(str), people.astype(str)),
                               data['expected']['center'], rtol=1e-10, atol=1e-12)
